library(arrow)
library(xgboost)
library(ggplot2)
library(data.table)
library(ggpattern)
library(latex2exp)
library(ggtext)
library(glue)
f <- function(...) as.character(glue::glue(...))
expit <- function(x) exp(x) / (1 + exp(x))
